language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=ember-2.3
- EMBER_TRY_SCENARIO=ember-2.4
- EMBER_TRY_SCENARIO=ember-2.5
- EMBER_TRY_SCENARIO=ember-2.6
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g bower
- npm install phantomjs-prebuilt
install:
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: heroku
  api_key:
    secure: QByfVZG0yt1m9l4JWbn556VmV5lCA1covgxizlE4ekw5y0UePa66MNMe9aTcxpxmOvTuut3Fv02Hgy1oJL5x93/vYADGk+YTVIXdN/DRSxS5wYNwzXRK74f+YMHSCyLvUWh2MJzz2+xs9L8813UjOWEyXu7WFh/Ic22xiMLBT7E=
  app: ember-materialize-demo
  on:
    repo: mike-north/ember-cli-materialize
    branch: v1
