---
language: node_js

node_js:
  - "0.12.2"

sudo: false

cache:
  directories:
    - node_modules

env:
  - E_SCENARIO=ember-1.10
  - E_SCENARIO=ember-release
  - E_SCENARIO=ember-beta
  - E_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: E_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $E_SCENARIO test
