language: node_js
node_js:
- 4
sudo: false
cache:
  directories:
  - node_modules

env:
- EMBER_TRY_SCENARIO=ember-1.13
- EMBER_TRY_SCENARIO=ember-2.4
- EMBER_TRY_SCENARIO=ember-2.6
- EMBER_TRY_SCENARIO=ember-release
- ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
- ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
  - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g bower
- npm install phantomjs-prebuilt
install:
- npm install -g bower
- npm install
- bower install
script:
- ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: heroku
  api_key:
    secure: JyCVhFlH+gDBkHoIivvBVNNIVuJSZT5jeFDHCBAhCMh2OsHCK99hlGtLJRjG6fPWwJ81jorUb14RDA5jxU/2VPeFvefelDqarkG3lWNUUnVtiFk2mDBuhYHW03P11btoixcg2NTr7cgNjARWEt4UbaZ1a0QkdzsmzhIbSjShrRk=
  app: ember-materialize-demo
  on:
    repo: mike-north/ember-cli-materialize
    condition: "$EMBER_TRY_SCENARIO = ember-release"
